services:
  # バックエンドサービス
  - type: web
    name: btpkun-backend
    env: node
    buildCommand: echo "No backend code yet"
    startCommand: echo "This is a placeholder service"
    envVars:
      - key: NODE_ENV
        value: production

  # フロントエンドサービス（静的サイトのプレースホルダー）
  - type: static
    name: btpkun
    buildCommand: echo "Building static placeholder"
    staticPublishPath: ./
    envVars:
      - key: REACT_APP_API_URL
        value: https://btpkun-backend.onrender.com
