services:
  # バックエンドサービス
  - type: web
    name: btpkun-backend
    env: node
    rootDir: backend  # backendディレクトリを指定
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
