services:
  # バックエンドサービス
  - type: web
    name: btpkun-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: FRONTEND_URL
        value: https://btpkun.onrender.com

  # フロントエンドサービス
  - type: web
    name: btpkun
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://btpkun-backend.onrender.com